# Generated by Django 2.0.2 on 2018-03-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_adress',
            new_name='NewAdress',
        ),
        migrations.RenameField(
            model_name='newadress',
            old_name='url_old',
            new_name='main_url',
        ),
    ]
